copy "%~dp0Source\Header.rb" + ^
     "%~dp0Source\Customization\Charge_Turn_Battle.rb" + ^
     "%~dp0Source\Customization\Scan_Skill.rb" + ^
     "%~dp0Source\Customization\Status_Icons.rb" + ^
     "%~dp0Source\Customization\Beastiary.rb" + ^
     "%~dp0Source\Customization\Input.rb" + ^
     "%~dp0Source\DataCheck.rb" + ^
     "%~dp0Source\CTB\GameObjects\Game_Battler.rb" + ^
     "%~dp0Source\CTB\GameObjects\Game_Enemy.rb" + ^
     "%~dp0Source\CTB\GameObjects\Game_Party.rb" + ^
     "%~dp0Source\CTB\Windows\Window_Base.rb" + ^
     "%~dp0Source\CTB\Windows\Window_Help.rb" + ^
     "%~dp0Source\CTB\Windows\Window_BigBattleStatus.rb" + ^
     "%~dp0Source\CTB\Windows\Window_TurnOrder.rb" + ^
     "%~dp0Source\CTB\Arrows\Arrow_All_Base.rb" + ^
     "%~dp0Source\CTB\Arrows\Arrow_All_Enemy.rb" + ^
     "%~dp0Source\CTB\Arrows\Arrow_All_Actor.rb" + ^
     "%~dp0Source\CTB\Scenes\Scene_Battle.rb" + ^
     "%~dp0Source\ScanSkill\Header.rb" + ^
     "%~dp0Source\ScanSkill\Game_Party.rb" + ^
     "%~dp0Source\ScanSkill\Scene_Battle.rb" + ^
     "%~dp0Source\ScanSkill\Mobius.rb" + ^
     "%~dp0Source\ScanSkill\Footer.rb" + ^
     "%~dp0Source\StatusIcons\Header.rb" + ^
     "%~dp0Source\StatusIcons\Window_Base.rb" + ^
     "%~dp0Source\StatusIcons\Window_Help.rb" + ^
     "%~dp0Source\StatusIcons\Footer.rb" + ^
     "%~dp0Source\Beastiary\Header.rb" + ^
     "%~dp0Source\Beastiary\Game_Enemy.rb" + ^
     "%~dp0Source\Beastiary\Windows\Window_BeastList.rb" + ^
     "%~dp0Source\Beastiary\Windows\Window_BeastMode.rb" + ^
     "%~dp0Source\Beastiary\Windows\Window_BeastInformation.rb" + ^
     "%~dp0Source\Beastiary\Windows\Window_BeastSprite.rb" + ^
     "%~dp0Source\Beastiary\Windows\Window_BeastStats.rb" + ^
     "%~dp0Source\Beastiary\Windows\Window_BeastElements.rb" + ^
     "%~dp0Source\Beastiary\Windows\Window_BeastStates.rb" + ^
     "%~dp0Source\Beastiary\Windows\Window_BeastDetail.rb" + ^
     "%~dp0Source\Beastiary\Windows\Window_BeastSubDetail.rb" + ^
     "%~dp0Source\Beastiary\Scene_Beastiary.rb" + ^
     "%~dp0Source\Beastiary\Footer.rb" + ^
     "%~dp0Source\RGSS\RGSS.rb" ^
     "%~dp0Mobius's CTB System.rb" /b /y